### ISSUE TITLE
AttributeError:module 'tensorrt' has no attribute 'PaddingMode'

### ISSUE THREAD

**Issue by ziweizhan** [NVIDIA-AI-IOT/torch2trt#133]
AttributeError:module 'tensorrt' has no attribute 'PaddingMode'

**Comment by jaybdub** [comment]
Hi ziweizhan,

Thanks for reaching out!  I would guess that you are using one of the pooling methods with ``ceil_mode=True``.  I believe this is only supported in TensorRT 5.1+.

Do you mind sharing which version of TensorRT you are using?

Best,
John

**Comment by ziweizhan** [comment]
Hi jaybdub，

When I upgraded the version of tensorrt to 5.1.2, this problem was solved. Thank you very much for your reply.

Best,
ziweizhan

**Comment by jaybdub** [comment]
Great to hear!  Thanks for letting me know.

Best,
John
