### ISSUE TITLE
Update torch2trt to work for tensorrt 10.8

### ISSUE THREAD

**Issue by monajalal** [NVIDIA-AI-IOT/torch2trt#954]
Could you please update torch2trt to work with TensorRT 10.8?

```
(sdgpose) 2025-02-11 16:36:45 [mona@DOS sdg_pallet_model]$ /home/mona/anaconda3/envs/sdgpose/bin/python predictor.py 
Traceback (most recent call last):
  File "/home/mona/sdg_pallet_model/predictor.py", line 3, in <module>
    import utils
  File "/home/mona/sdg_pallet_model/utils.py", line 22, in <module>
    import torch2trt
  File "/home/mona/anaconda3/envs/sdgpose/lib/python3.10/site-packages/torch2trt-0.5.0-py3.10.egg/torch2trt/__init__.py", line 1, in <module>
    from .torch2trt import *
  File "/home/mona/anaconda3/envs/sdgpose/lib/python3.10/site-packages/torch2trt-0.5.0-py3.10.egg/torch2trt/torch2trt.py", line 9, in <module>
    from .dataset_calibrator import (
  File "/home/mona/anaconda3/envs/sdgpose/lib/python3.10/site-packages/torch2trt-0.5.0-py3.10.egg/torch2trt/dataset_calibrator.py", line 12, in <module>
    DEFAULT_CALIBRATION_ALGORITHM = trt.CalibrationAlgoType.ENTROPY_CALIBRATION_2
AttributeError: module 'tensorrt' has no attribute 'CalibrationAlgoType'

```

I removed version related lines and installed it however, it is way more problems.

I can also see that we have this in trt 10.8 so not sure about the reason for error??

![Image](https://github.com/user-attachments/assets/6905b013-6a59-413b-af95-8e2ab4b6b87a)

https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Int8/Calibrator.html#iint8calibrator
